---
- name: Install pre-requisites
  yum:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - unzip
      - lftp
      - ftp

- name: Create temporary dir for installer.
  file:
    path: "/tmp/vscl/"
    state: directory
    mode: '0755'

- name: Download and extract McAfee Virus Scan for Enterprise Linux
  get_url:
    url: "{{ uvscan_download_url }}"
    dest: "/tmp/vscl/"
  register: mcafee_download

- name: Extract McAfee VSCL
  unarchive:
    src: "{{ mcafee_download.dest }}"
    dest: "/tmp/vscl/"
    remote_src: yes

- name: Determine if McAfee VSCL is installed
  command: "/usr/local/bin/uvscan --version"
  register: uvscan_installed
  ignore_errors: yes
  changed_when: false

- name: Install McAfee VSCL  # noqa 301 305
  shell:
    cmd: ./install-uvscan -y
    chdir: "/tmp/vscl/"
  when: uvscan_installed is failed

- name: Configure LFTP Proxy
  template:
    src: templates/lftp.conf.j2
    dest: /etc/lftp.conf
    owner: root
    group: root
    mode: '0755'
  when: ftp_proxy | bool

- name: Copy update script
  template:
    src: templates/mcafee_update.sh.j2
    dest: /usr/local/uvscan/mcafee_update.sh
    owner: root
    group: root
    mode: '0755'

- name: Run Update Script to setup initial dat files  # noqa 301 305
  shell:
    cmd: /usr/local/uvscan/mcafee_update.sh
  when: uvscan_installed is failed

- name: Setup Update CronJob
  cron:
    name: "Update McAfee DAT Files"
    minute: "0"
    hour: "3"
    job: "/usr/local/uvscan/mcafee_update.sh "
