---
- name: Converge
  hosts: all
  become: true

  vars:    
    # Role: yum_config_manager
    repositories:
      enabled:
        - rhui-REGION-rhel-server-rhscl
        - rhui-REGION-rhel-server-debug-rhscl

    # Role: UVScan
    uvscan_download_url: "{{ lookup('env', 'UVSCAN_DOWNLOAD_URL') }}"

  roles:
    - role: nycrecords.yum_config_manager
    - role: ansible-role-uvscan